name: cfetter
favicon: null
layout_spectrum: 0.17335217585787177
typography_spectrum: 0.694423439912498
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.04303488926962018
  lightness: 0.4768930389545858
  saturation: 0.09385825786739588
  rhythmicContrast: 0.1784908485133201
purpose: []
